  - name: Install MariaDB package (CentOS)
    tags: centos,db,mariadb
    dnf:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "CentOS"

  - name: Install MariaDB package (Ubuntu)
    tags: db,mariadb,ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: "Mariadb - Restarting/Enabling"
    tags: centos,db,mariadb
    systemd:
      name: mariadb
      enabled: yes
      state: restarted
